### PR TITLE
Light Color Scheme

### PR DESCRIPTION
**Pull request by CODEDESIGNSE0**
Changing darks to lights, and lights to darks.

Maybe a few things to optimize/adjust.  But it looks good now.

### CODE REVIEW

**Comment by CODEDESIGNSE0** [comment]
heading to work soon, just wanted you guys to get this and hopefully make the change.  That black bg has GOTTA go.  alright, enjoy your night!

**Comment by ghost** [comment]
You are pulling this into master, which is live code.  Pull it into a branch.

**Comment by CODEDESIGNSE0** [comment]
Whoops, sorry!  Any preferred branch?

**Comment by ghost** [comment]
Let me make one real fast.

**Comment by ghost** [comment]
Pull here --> https://github.com/KeepOurNetFree/keepournetfree.github.io/tree/CODEDESIGNSE0

**Pull request closed without merging**
