### PR TITLE
New Background Images

### PR DESCRIPTION
**Pull request by jacobherrington**
refs #19 

Both images should be free to use, even for commercial purposes.

### CODE REVIEW

**Comment by ghost** [comment]
Are you in our IRC?  
http://irc.lc/snoonet/KeepOurNetFree/#irc

**Comment by jacobherrington** [comment]
@DailyDoseOfAwesome yeah, I dropped in for a bit.

**Comment by ghost** [comment]
Ah, it looks like you are using an old version of test-environment.  Somehow it got borked and we had to blow it away.  7 ahead | 5 behind and was causing merge conflicts.

lol.  Something didn't merge right --> http://i.imgur.com/8hB16s9.png

**Comment by jacobherrington** [comment]
Got you, I'll fork master and fix that at some point today.

**Pull request closed without merging**
